#!/usr/bin/env bash
# installs nginx and configures it on a remote server (nginx)
apt-get update
apt-get install -y nginx
sed -i 's/listen 80 77125-web-01;/listen 80;/' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
/etc/init.d/nginx restart
curl 127.0.0.1
