#!/usr/bin/env bash
# installs nginx and configures it on a remote server (nginx)
# update package list
apt-get update

# install nginx
apt-get install -y nginx

# configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
/etc/init.d/nginx restart
curl localhost
