#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
touch /etc/nginx/conf.d/redirect.conf

# Add the redirection rule to the new configuration file
echo "server {listen 80; 77125-web-01 _; location /redirect_me {return 301 http://google.com;}}" >> /etc/nginx/conf.d/redirect.conf
nginx -t
/etc/init.d/nginx restart
