#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/4-not_found_page_404.html
sed -i 's/4-not_found_page_404/4-not_found_page_404 \/4-not_found_page_404.html;/g' /etc/nginx/sites-available/default
service nginx start
