#!/usr/bin/env bash
# sets up firewall to block all incoming traffic EXCEPT TCP ports '22, 443 and 80'
# and redirects port 8080/TCP to port 80/TCP
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw allow 8080/tcp
sudo ufw redirect 8080/tcp to 80/tcp
sudo ufw enable
